name: Processor deployment trigger

on:
  push:
    tags:
      - "[0-9][0-9][0-9][0-9].[0-9][0-9].[0-9][0-9]*"
  workflow_dispatch:

jobs:
  exec-deployment:
    if: github.ref_type == 'tag'
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
