changelog:
  categories:
    - title: Performance Improvements ⚡
      labels:
        - 'meta:performance'
    - title: New Features ✅
      labels:
        - 'pr:feature'
    - title: Bug Fixes 🔧
      labels:
        - 'pr:bug'
    - title: Misc. Fixes 🚧
      labels:
        - '*'
