[package]
name = "otr-beatmap-duration"
version = "1.0.0"
edition = "2024"
publish = false
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rosu-pp = "=4.0.1"
rosu-map = "=0.2.1"
wasm-bindgen = "=0.2.100"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
strip = true
