declare namespace NodeJS {
  interface ProcessEnv {
    DATA_WORKER_OSU_CLIENT_ID: string;
    DATA_WORKER_OSU_CLIENT_SECRET: string;
    RABBITMQ_AMQP_URL: string;
    DATABASE_URL: string;
    OSU_API_RATE_LIMIT_REQUESTS: string;
    OSU_API_RATE_LIMIT_WINDOW_SECONDS: string;
    OSUTRACK_API_RATE_LIMIT_REQUESTS: string;
    OSUTRACK_API_RATE_LIMIT_WINDOW_SECONDS: string;
    BEATMAP_FILE_FETCH_ENABLED: string;
    PLAYER_OSU_AUTO_REFETCH_ENABLED: string;
    PLAYER_OSU_REFETCH_INTERVAL_MINUTES: string;
    PLAYER_OSU_REFETCH_OUTDATED_DAYS: string;
    PLAYER_OSUTRACK_AUTO_REFETCH_ENABLED: string;
    PLAYER_OSUTRACK_REFETCH_INTERVAL_MINUTES: string;
    PLAYER_OSUTRACK_REFETCH_OUTDATED_DAYS: string;
  }
}
