name: Web deployment trigger
on:
  push:
    branches:
      - master
    tags:
      - '[0-9][0-9][0-9][0-9].[0-9][0-9].[0-9][0-9]*'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'Staging'
        type: choice
        options:
          - Staging
          - Production
jobs:
  determine-environment:
    runs-on: ubuntu-latest
    outputs:
      target: ${{ steps.env.outputs.target }}
    steps:
      - name: Determine environment
        id: env
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "target=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "target=Staging" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" =~ refs/tags/[0-9]{4}\.[0-9]{2}\.[0-9]{2} ]]; then
            echo "target=Production" >> $GITHUB_OUTPUT
          else
            echo "target=none" >> $GITHUB_OUTPUT
          fi

  exec-deployment:
    needs: determine-environment
    if: needs.determine-environment.outputs.target != 'none'
    uses: osu-tournament-rating/otr-web/.github/workflows/deploy.yml@master
    with:
      target: ${{ needs.determine-environment.outputs.target }}
    secrets: inherit
